version: '3.8'

services:
  app:
    image: nofefloresmo/caso:caso-app-tag
    #build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis02
      - mongo01
      - mongo02
      - mongo03
      - mongo-init-replica
    networks:
      - red02
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis02:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - red02

  mongo01:
    image: mongo:latest
    command: [ "mongod", "--replSet", "replica01" ]
    ports:
      - "27020:27017"
    networks:
      - red02

  mongo02:
    image: mongo:latest
    command: [ "mongod", "--replSet", "replica01" ]
    ports:
      - "27021:27017"
    networks:
      - red02

  mongo03:
    image: mongo:latest
    command: [ "mongod", "--replSet", "replica01" ]
    ports:
      - "27022:27017"
    networks:
      - red02

  mongo-init-replica:
    image: nofefloresmo/caso:caso-mongo-init-replica-tag
    depends_on:
      - mongo01
      - mongo02
      - mongo03
    networks:
      - red02

networks:
  red02:
